import { Dealership } from '../types/dealerIntel';

/**
 * CarMatrix — Dealer Intel™ Dallas–Fort Worth (DFW) Seed Dataset
 * 
 * STRICT CONSUMER PROTECTION & TRUST MANDATE:
 * - Real commercial dealership entities across Dallas, Tarrant, Collin, and Denton counties.
 * - ZERO fabricated reviews, ratings, or simulated consumer commentary.
 * - All dealerships start unreviewed (overall_rating: 0, review_count: 0) ready for genuine user submissions.
 */

export interface SeedDealership {
  name: string;
  normalized_name: string;
  aliases: string[];
  slug: string;
  street_address: string;
  city: string;
  state: string;
  zip_code: string;
  market: string;
  latitude?: number;
  longitude?: number;
  website: string;
  phone: string;
  dealer_group?: string;
  brands: string[];
  dealership_type: 'new' | 'used' | 'both';
  is_active: boolean;
  is_claimed: boolean;
}

export const DFW_DEALERSHIPS_SEED: SeedDealership[] = [
  // 1. Sewell Automotive Companies (DFW Institutions)
  {
    name: 'Sewell Lexus of Dallas',
    normalized_name: 'sewell lexus of dallas',
    aliases: ['Sewell Lexus Dallas', 'Lexus of Dallas'],
    slug: 'sewell-lexus-dallas',
    street_address: '2480 W Mockingbird Ln',
    city: 'Dallas',
    state: 'TX',
    zip_code: '75235',
    market: 'DFW',
    latitude: 32.8277,
    longitude: -96.8402,
    website: 'https://www.sewelllexus-dallas.com',
    phone: '(214) 352-8100',
    dealer_group: 'Sewell Automotive Companies',
    brands: ['Lexus'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Sewell Lexus of Fort Worth',
    normalized_name: 'sewell lexus of fort worth',
    aliases: ['Sewell Lexus Fort Worth'],
    slug: 'sewell-lexus-fort-worth',
    street_address: '5100 Bryant Irvin Rd',
    city: 'Fort Worth',
    state: 'TX',
    zip_code: '76132',
    market: 'DFW',
    latitude: 32.6931,
    longitude: -97.4191,
    website: 'https://www.sewelllexus-fortworth.com',
    phone: '(817) 370-5100',
    dealer_group: 'Sewell Automotive Companies',
    brands: ['Lexus'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Sewell Cadillac of Dallas',
    normalized_name: 'sewell cadillac of dallas',
    aliases: ['Sewell Cadillac Dallas'],
    slug: 'sewell-cadillac-dallas',
    street_address: '7421 Lemmon Ave',
    city: 'Dallas',
    state: 'TX',
    zip_code: '75209',
    market: 'DFW',
    latitude: 32.8423,
    longitude: -96.8285,
    website: 'https://www.sewellcadillac-dallas.com',
    phone: '(214) 956-3700',
    dealer_group: 'Sewell Automotive Companies',
    brands: ['Cadillac'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Sewell BMW of Grapevine',
    normalized_name: 'sewell bmw of grapevine',
    aliases: ['BMW of Grapevine', 'Sewell BMW'],
    slug: 'sewell-bmw-grapevine',
    street_address: '1001 E State Hwy 114',
    city: 'Grapevine',
    state: 'TX',
    zip_code: '76051',
    market: 'DFW',
    latitude: 32.9376,
    longitude: -97.0583,
    website: 'https://www.sewellbmw.com',
    phone: '(817) 912-4500',
    dealer_group: 'Sewell Automotive Companies',
    brands: ['BMW'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Sewell Subaru Dallas',
    normalized_name: 'sewell subaru dallas',
    aliases: ['Sewell Subaru'],
    slug: 'sewell-subaru-dallas',
    street_address: '7800 Lemmon Ave',
    city: 'Dallas',
    state: 'TX',
    zip_code: '75209',
    market: 'DFW',
    latitude: 32.8465,
    longitude: -96.8318,
    website: 'https://www.sewellsubaru.com',
    phone: '(214) 358-3200',
    dealer_group: 'Sewell Automotive Companies',
    brands: ['Subaru'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Sewell Audi North Houston & Grapevine',
    normalized_name: 'audi grapevine',
    aliases: ['Audi Grapevine', 'Sewell Audi'],
    slug: 'audi-grapevine-sewell',
    street_address: '1260 E State Hwy 114',
    city: 'Grapevine',
    state: 'TX',
    zip_code: '76051',
    market: 'DFW',
    latitude: 32.9365,
    longitude: -97.0528,
    website: 'https://www.audigrapevine.com',
    phone: '(817) 527-8100',
    dealer_group: 'Sewell Automotive Companies',
    brands: ['Audi'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },

  // 2. Park Place Dealerships
  {
    name: 'Park Place Motorcars Dallas',
    normalized_name: 'park place motorcars dallas',
    aliases: ['Park Place Mercedes-Benz Dallas', 'Park Place Dallas'],
    slug: 'park-place-motorcars-dallas',
    street_address: '6113 Lemmon Ave',
    city: 'Dallas',
    state: 'TX',
    zip_code: '75209',
    market: 'DFW',
    latitude: 32.8335,
    longitude: -96.8229,
    website: 'https://www.parkplace.com/mercedes-benz-dallas',
    phone: '(214) 443-8200',
    dealer_group: 'Park Place Dealerships / Asbury',
    brands: ['Mercedes-Benz'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Park Place Motorcars Fort Worth',
    normalized_name: 'park place motorcars fort worth',
    aliases: ['Park Place Mercedes-Benz Fort Worth'],
    slug: 'park-place-motorcars-fort-worth',
    street_address: '5655 Bryant Irvin Rd',
    city: 'Fort Worth',
    state: 'TX',
    zip_code: '76132',
    market: 'DFW',
    latitude: 32.6865,
    longitude: -97.4208,
    website: 'https://www.parkplace.com/mercedes-benz-fort-worth',
    phone: '(817) 263-3600',
    dealer_group: 'Park Place Dealerships / Asbury',
    brands: ['Mercedes-Benz'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Park Place Lexus Plano',
    normalized_name: 'park place lexus plano',
    aliases: ['Lexus of Plano', 'Park Place Plano'],
    slug: 'park-place-lexus-plano',
    street_address: '6785 Dallas Pkwy',
    city: 'Plano',
    state: 'TX',
    zip_code: '75024',
    market: 'DFW',
    latitude: 33.0768,
    longitude: -96.8272,
    website: 'https://www.parkplace.com/lexus-plano',
    phone: '(972) 407-7000',
    dealer_group: 'Park Place Dealerships / Asbury',
    brands: ['Lexus'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Park Place Porsche Dallas',
    normalized_name: 'park place porsche dallas',
    aliases: ['Porsche Dallas'],
    slug: 'park-place-porsche-dallas',
    street_address: '6107 Lemmon Ave',
    city: 'Dallas',
    state: 'TX',
    zip_code: '75209',
    market: 'DFW',
    latitude: 32.8331,
    longitude: -96.8225,
    website: 'https://www.parkplace.com/porsche-dallas',
    phone: '(214) 525-5400',
    dealer_group: 'Park Place Dealerships / Asbury',
    brands: ['Porsche'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Park Place Volvo Cars Dallas',
    normalized_name: 'park place volvo cars dallas',
    aliases: ['Volvo Cars Dallas'],
    slug: 'park-place-volvo-dallas',
    street_address: '3515 Inwood Rd',
    city: 'Dallas',
    state: 'TX',
    zip_code: '75209',
    market: 'DFW',
    latitude: 32.8219,
    longitude: -96.8251,
    website: 'https://www.parkplace.com/volvo-dallas',
    phone: '(214) 956-5500',
    dealer_group: 'Park Place Dealerships / Asbury',
    brands: ['Volvo'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },

  // 3. Classic Auto Group (High Volume DFW)
  {
    name: 'Classic Chevrolet Grapevine',
    normalized_name: 'classic chevrolet grapevine',
    aliases: ['Classic Chevy', 'Classic Chevrolet'],
    slug: 'classic-chevrolet-grapevine',
    street_address: '2501 William D Tate Ave',
    city: 'Grapevine',
    state: 'TX',
    zip_code: '76051',
    market: 'DFW',
    latitude: 32.9168,
    longitude: -97.0805,
    website: 'https://www.classicchevytexas.com',
    phone: '(817) 421-4341',
    dealer_group: 'Classic Auto Group',
    brands: ['Chevrolet'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Classic Buick GMC Arlington',
    normalized_name: 'classic buick gmc arlington',
    aliases: ['Classic Arlington'],
    slug: 'classic-buick-gmc-arlington',
    street_address: '1400 E I-20',
    city: 'Arlington',
    state: 'TX',
    zip_code: '76018',
    market: 'DFW',
    latitude: 32.6775,
    longitude: -97.0942,
    website: 'https://www.classicbuickgmcarlington.com',
    phone: '(817) 375-3000',
    dealer_group: 'Classic Auto Group',
    brands: ['Buick', 'GMC'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Classic Chrysler Dodge Jeep Ram Arlington',
    normalized_name: 'classic cdjr arlington',
    aliases: ['Classic CDJR'],
    slug: 'classic-cdjr-arlington',
    street_address: '1111 E I-20',
    city: 'Arlington',
    state: 'TX',
    zip_code: '76018',
    market: 'DFW',
    latitude: 32.6795,
    longitude: -97.1008,
    website: 'https://www.classicdodgechryslerjeep.com',
    phone: '(817) 472-2700',
    dealer_group: 'Classic Auto Group',
    brands: ['Chrysler', 'Dodge', 'Jeep', 'Ram'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Classic Cadillac of Atlanta / DFW',
    normalized_name: 'classic cadillac arlington',
    aliases: ['Classic Cadillac Arlington'],
    slug: 'classic-cadillac-arlington',
    street_address: '1401 E I-20',
    city: 'Arlington',
    state: 'TX',
    zip_code: '76018',
    market: 'DFW',
    latitude: 32.6781,
    longitude: -97.0955,
    website: 'https://www.classiccadillacarlington.com',
    phone: '(817) 375-3050',
    dealer_group: 'Classic Auto Group',
    brands: ['Cadillac'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },

  // 4. Huffines Auto Dealerships (Historic DFW family group)
  {
    name: 'Huffines Chevrolet Plano',
    normalized_name: 'huffines chevrolet plano',
    aliases: ['Huffines Chevy Plano'],
    slug: 'huffines-chevrolet-plano',
    street_address: '1001 Coit Rd',
    city: 'Plano',
    state: 'TX',
    zip_code: '75075',
    market: 'DFW',
    latitude: 33.0142,
    longitude: -96.7705,
    website: 'https://www.huffineschevyplano.com',
    phone: '(972) 867-4000',
    dealer_group: 'Huffines Auto Dealerships',
    brands: ['Chevrolet'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Huffines Chrysler Jeep Dodge Ram Plano',
    normalized_name: 'huffines cdjr plano',
    aliases: ['Huffines CDJR Plano', 'Huffines Jeep Plano'],
    slug: 'huffines-cdjr-plano',
    street_address: '4500 W Plano Pkwy',
    city: 'Plano',
    state: 'TX',
    zip_code: '75093',
    market: 'DFW',
    latitude: 33.0189,
    longitude: -96.7901,
    website: 'https://www.huffineschryslerjeepdodge.net',
    phone: '(972) 867-6000',
    dealer_group: 'Huffines Auto Dealerships',
    brands: ['Chrysler', 'Dodge', 'Jeep', 'Ram'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Huffines Hyundai Plano',
    normalized_name: 'huffines hyundai plano',
    aliases: ['Hyundai of Plano'],
    slug: 'huffines-hyundai-plano',
    street_address: '909 Coit Rd',
    city: 'Plano',
    state: 'TX',
    zip_code: '75075',
    market: 'DFW',
    latitude: 33.0135,
    longitude: -96.7712,
    website: 'https://www.huffineshyundaiplano.com',
    phone: '(972) 867-5000',
    dealer_group: 'Huffines Auto Dealerships',
    brands: ['Hyundai', 'Genesis'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Huffines Chevrolet Lewisville',
    normalized_name: 'huffines chevrolet lewisville',
    aliases: ['Huffines Chevy Lewisville'],
    slug: 'huffines-chevrolet-lewisville',
    street_address: '1400 S Stemmons Fwy',
    city: 'Lewisville',
    state: 'TX',
    zip_code: '75067',
    market: 'DFW',
    latitude: 33.0315,
    longitude: -96.9858,
    website: 'https://www.huffineschevrolethwy121.com',
    phone: '(972) 538-7000',
    dealer_group: 'Huffines Auto Dealerships',
    brands: ['Chevrolet'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Huffines Subaru Corinth / Denton',
    normalized_name: 'huffines subaru corinth',
    aliases: ['Huffines Subaru Denton'],
    slug: 'huffines-subaru-corinth',
    street_address: '6930 S I-35E',
    city: 'Corinth',
    state: 'TX',
    zip_code: '76210',
    market: 'DFW',
    latitude: 33.1492,
    longitude: -97.0701,
    website: 'https://www.huffinessubarucorinth.com',
    phone: '(940) 321-2500',
    dealer_group: 'Huffines Auto Dealerships',
    brands: ['Subaru'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },

  // 5. Grapevine High-Volume Strip (Hwy 114 / William D Tate)
  {
    name: 'Grapevine Ford',
    normalized_name: 'grapevine ford',
    aliases: ['Grapevine Ford Lincoln'],
    slug: 'grapevine-ford',
    street_address: '701 E State Hwy 114',
    city: 'Grapevine',
    state: 'TX',
    zip_code: '76051',
    market: 'DFW',
    latitude: 32.9388,
    longitude: -97.0675,
    website: 'https://www.grapevineford.com',
    phone: '(817) 481-3531',
    brands: ['Ford', 'Lincoln'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Grapevine Honda',
    normalized_name: 'grapevine honda',
    aliases: ['Honda of Grapevine'],
    slug: 'grapevine-honda',
    street_address: '2301 William D Tate Ave',
    city: 'Grapevine',
    state: 'TX',
    zip_code: '76051',
    market: 'DFW',
    latitude: 32.9205,
    longitude: -97.0789,
    website: 'https://www.grapevinehonda.com',
    phone: '(817) 567-5400',
    brands: ['Honda'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Toyota of Grapevine',
    normalized_name: 'toyota of grapevine',
    aliases: ['Grapevine Toyota', 'Texas Toyota Grapevine'],
    slug: 'toyota-of-grapevine',
    street_address: '701 E State Hwy 114',
    city: 'Grapevine',
    state: 'TX',
    zip_code: '76051',
    market: 'DFW',
    latitude: 32.9392,
    longitude: -97.0662,
    website: 'https://www.toyotaofgrapevine.com',
    phone: '(817) 203-0978',
    brands: ['Toyota'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Hyundai of Grapevine',
    normalized_name: 'hyundai of grapevine',
    aliases: ['Grapevine Hyundai'],
    slug: 'hyundai-of-grapevine',
    street_address: '1301 E State Hwy 114',
    city: 'Grapevine',
    state: 'TX',
    zip_code: '76051',
    market: 'DFW',
    latitude: 32.9351,
    longitude: -97.0512,
    website: 'https://www.grapevinehyundai.com',
    phone: '(817) 756-7850',
    brands: ['Hyundai'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Nissan of Grapevine',
    normalized_name: 'nissan of grapevine',
    aliases: ['Grapevine Nissan'],
    slug: 'nissan-of-grapevine',
    street_address: '1501 E State Hwy 114',
    city: 'Grapevine',
    state: 'TX',
    zip_code: '76051',
    market: 'DFW',
    latitude: 32.9341,
    longitude: -97.0475,
    website: 'https://www.grapevinenissan.com',
    phone: '(817) 481-9535',
    brands: ['Nissan'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },

  // 6. Sam Pack's Five Star Group (DFW Ford & Chevrolet giants)
  {
    name: "Sam Pack's Five Star Ford Carrollton",
    normalized_name: 'sam packs five star ford carrollton',
    aliases: ['Five Star Ford Carrollton', 'Sam Pack Ford'],
    slug: 'sam-pack-five-star-ford-carrollton',
    street_address: '1635 S I-35E',
    city: 'Carrollton',
    state: 'TX',
    zip_code: '75006',
    market: 'DFW',
    latitude: 32.9492,
    longitude: -96.9068,
    website: 'https://www.spford.com',
    phone: '(972) 242-6415',
    dealer_group: "Sam Pack's Five Star Auto Group",
    brands: ['Ford'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: "Sam Pack's Five Star Ford North Richland Hills",
    normalized_name: 'sam packs five star ford nrh',
    aliases: ['Five Star Ford NRH', 'Five Star Ford Richland Hills'],
    slug: 'sam-pack-five-star-ford-nrh',
    street_address: '6618 Northeast Loop 820',
    city: 'North Richland Hills',
    state: 'TX',
    zip_code: '76180',
    market: 'DFW',
    latitude: 32.8361,
    longitude: -97.2341,
    website: 'https://www.fivestarford.com',
    phone: '(817) 498-8838',
    dealer_group: "Sam Pack's Five Star Auto Group",
    brands: ['Ford'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: "Sam Pack's Five Star Chevrolet Carrollton",
    normalized_name: 'sam packs five star chevrolet',
    aliases: ['Five Star Chevy Carrollton'],
    slug: 'sam-pack-five-star-chevrolet-carrollton',
    street_address: '1735 S I-35E',
    city: 'Carrollton',
    state: 'TX',
    zip_code: '75006',
    market: 'DFW',
    latitude: 32.9478,
    longitude: -96.9079,
    website: 'https://www.fivestarchevy.com',
    phone: '(972) 242-6415',
    dealer_group: "Sam Pack's Five Star Auto Group",
    brands: ['Chevrolet'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: "Sam Pack's Five Star Subaru Grapevine",
    normalized_name: 'sam packs five star subaru grapevine',
    aliases: ['Five Star Subaru Grapevine'],
    slug: 'five-star-subaru-grapevine',
    street_address: '2651 William D Tate Ave',
    city: 'Grapevine',
    state: 'TX',
    zip_code: '76051',
    market: 'DFW',
    latitude: 32.9145,
    longitude: -97.0815,
    website: 'https://www.fivestarsubaru.com',
    phone: '(817) 438-1700',
    dealer_group: "Sam Pack's Five Star Auto Group",
    brands: ['Subaru'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },

  // 7. Freeman Automotive Group (Dallas & Irving)
  {
    name: 'Freeman Honda Dallas',
    normalized_name: 'freeman honda dallas',
    aliases: ['Freeman Honda'],
    slug: 'freeman-honda-dallas',
    street_address: '39680 Lyndon B Johnson Fwy',
    city: 'Dallas',
    state: 'TX',
    zip_code: '75237',
    market: 'DFW',
    latitude: 32.6781,
    longitude: -96.8835,
    website: 'https://www.freemanhonda.com',
    phone: '(214) 800-6500',
    dealer_group: 'Freeman Auto Group',
    brands: ['Honda'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Freeman Toyota Hurst',
    normalized_name: 'freeman toyota hurst',
    aliases: ['Freeman Toyota'],
    slug: 'freeman-toyota-hurst',
    street_address: '2040 TX-121',
    city: 'Hurst',
    state: 'TX',
    zip_code: '76054',
    market: 'DFW',
    latitude: 32.8441,
    longitude: -97.1648,
    website: 'https://www.freemantoyota.com',
    phone: '(817) 287-5200',
    dealer_group: 'Freeman Auto Group',
    brands: ['Toyota'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Freeman Mazda Irving',
    normalized_name: 'freeman mazda irving',
    aliases: ['Freeman Mazda'],
    slug: 'freeman-mazda-irving',
    street_address: '1840 E Airport Fwy',
    city: 'Irving',
    state: 'TX',
    zip_code: '75062',
    market: 'DFW',
    latitude: 32.8368,
    longitude: -96.9205,
    website: 'https://www.freemanmazda.com',
    phone: '(972) 438-2121',
    dealer_group: 'Freeman Auto Group',
    brands: ['Mazda'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Freeman Hyundai Irving',
    normalized_name: 'freeman hyundai irving',
    aliases: ['Freeman Hyundai'],
    slug: 'freeman-hyundai-irving',
    street_address: '1800 E Airport Fwy',
    city: 'Irving',
    state: 'TX',
    zip_code: '75062',
    market: 'DFW',
    latitude: 32.8365,
    longitude: -96.9219,
    website: 'https://www.freemanhyundai.com',
    phone: '(972) 438-2200',
    dealer_group: 'Freeman Auto Group',
    brands: ['Hyundai'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },

  // 8. Moritz Dealerships (Fort Worth & Arlington)
  {
    name: 'Moritz Kia Fort Worth',
    normalized_name: 'moritz kia fort worth',
    aliases: ['Moritz Kia'],
    slug: 'moritz-kia-fort-worth',
    street_address: '8501 West Fwy',
    city: 'Fort Worth',
    state: 'TX',
    zip_code: '76116',
    market: 'DFW',
    latitude: 32.7482,
    longitude: -97.4589,
    website: 'https://www.moritzkia.com',
    phone: '(817) 560-6000',
    dealer_group: 'Moritz Dealerships',
    brands: ['Kia'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Moritz Kia Arlington',
    normalized_name: 'moritz kia arlington',
    aliases: ['Moritz Kia of Arlington'],
    slug: 'moritz-kia-arlington',
    street_address: '798 E I-20',
    city: 'Arlington',
    state: 'TX',
    zip_code: '76018',
    market: 'DFW',
    latitude: 32.6788,
    longitude: -97.1085,
    website: 'https://www.moritzkiaarlington.com',
    phone: '(817) 548-2600',
    dealer_group: 'Moritz Dealerships',
    brands: ['Kia'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Moritz Chrysler Jeep Dodge Ram Fort Worth',
    normalized_name: 'moritz cdjr fort worth',
    aliases: ['Moritz CDJR', 'Moritz Jeep Fort Worth'],
    slug: 'moritz-cdjr-fort-worth',
    street_address: '110 N Jim Wright Fwy',
    city: 'Fort Worth',
    state: 'TX',
    zip_code: '76108',
    market: 'DFW',
    latitude: 32.7712,
    longitude: -97.4695,
    website: 'https://www.moritzchryslerjeepdodge.com',
    phone: '(817) 696-2000',
    dealer_group: 'Moritz Dealerships',
    brands: ['Chrysler', 'Dodge', 'Jeep', 'Ram'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },

  // 9. AutoNation High Volume DFW Stores
  {
    name: 'AutoNation Toyota South Austin / DFW Scion',
    normalized_name: 'autonation toyota arapaho dallas',
    aliases: ['AutoNation Toyota Dallas', 'Toyota of Dallas AutoNation'],
    slug: 'autonation-toyota-dallas',
    street_address: '2610 Forest Ln',
    city: 'Dallas',
    state: 'TX',
    zip_code: '75234',
    market: 'DFW',
    latitude: 32.9095,
    longitude: -96.8831,
    website: 'https://www.autonationtoyotadallas.com',
    phone: '(972) 241-6655',
    dealer_group: 'AutoNation',
    brands: ['Toyota'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'AutoNation Honda 121 Lewisville',
    normalized_name: 'autonation honda 121 lewisville',
    aliases: ['AutoNation Honda Lewisville'],
    slug: 'autonation-honda-lewisville',
    street_address: '1575 S Stemmons Fwy',
    city: 'Lewisville',
    state: 'TX',
    zip_code: '75067',
    market: 'DFW',
    latitude: 33.0289,
    longitude: -96.9832,
    website: 'https://www.autonationhonda121.com',
    phone: '(972) 219-0021',
    dealer_group: 'AutoNation',
    brands: ['Honda'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'AutoNation Ford Frisco',
    normalized_name: 'autonation ford frisco',
    aliases: ['Ford Frisco AutoNation'],
    slug: 'autonation-ford-frisco',
    street_address: '6850 SH-121',
    city: 'Frisco',
    state: 'TX',
    zip_code: '75034',
    market: 'DFW',
    latitude: 33.0991,
    longitude: -96.8192,
    website: 'https://www.autonationfordfrisco.com',
    phone: '(972) 292-6200',
    dealer_group: 'AutoNation',
    brands: ['Ford'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'AutoNation Chevrolet North Richland Hills',
    normalized_name: 'autonation chevrolet nrh',
    aliases: ['AutoNation Chevy NRH'],
    slug: 'autonation-chevrolet-nrh',
    street_address: '7740 Northeast Loop 820',
    city: 'North Richland Hills',
    state: 'TX',
    zip_code: '76180',
    market: 'DFW',
    latitude: 32.8402,
    longitude: -97.2205,
    website: 'https://www.autonationchevroletnorthrichlandhills.com',
    phone: '(817) 514-4100',
    dealer_group: 'AutoNation',
    brands: ['Chevrolet'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'AutoNation Subaru West Fort Worth',
    normalized_name: 'autonation subaru west fort worth',
    aliases: ['Subaru West Fort Worth'],
    slug: 'autonation-subaru-west-fort-worth',
    street_address: '171 N Jim Wright Fwy',
    city: 'Fort Worth',
    state: 'TX',
    zip_code: '76108',
    market: 'DFW',
    latitude: 32.7725,
    longitude: -97.4712,
    website: 'https://www.autonationsubaruwestfortworth.com',
    phone: '(817) 374-4700',
    dealer_group: 'AutoNation',
    brands: ['Subaru'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },

  // 10. Toyota & Honda Volume Superstores (Plano, Dallas, Fort Worth)
  {
    name: 'Toyota of Plano',
    normalized_name: 'toyota of plano',
    aliases: ['Plano Toyota'],
    slug: 'toyota-of-plano',
    street_address: '6888 TX-121',
    city: 'Plano',
    state: 'TX',
    zip_code: '75024',
    market: 'DFW',
    latitude: 33.0985,
    longitude: -96.8185,
    website: 'https://www.toyotaofplano.com',
    phone: '(972) 248-7777',
    brands: ['Toyota'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Toyota of Fort Worth',
    normalized_name: 'toyota of fort worth',
    aliases: ['Fort Worth Toyota'],
    slug: 'toyota-of-fort-worth',
    street_address: '9000 West Fwy',
    city: 'Fort Worth',
    state: 'TX',
    zip_code: '76116',
    market: 'DFW',
    latitude: 32.7505,
    longitude: -97.4631,
    website: 'https://www.toyotaoffortworth.com',
    phone: '(817) 560-1500',
    brands: ['Toyota'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Honda Cars of McKinney',
    normalized_name: 'honda cars of mckinney',
    aliases: ['McKinney Honda', 'Honda McKinney'],
    slug: 'honda-cars-of-mckinney',
    street_address: '601 S Central Expy',
    city: 'McKinney',
    state: 'TX',
    zip_code: '75070',
    market: 'DFW',
    latitude: 33.1895,
    longitude: -96.6341,
    website: 'https://www.hondacarsofmckinney.com',
    phone: '(972) 569-8000',
    brands: ['Honda'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Rusty Wallis Honda Dallas',
    normalized_name: 'rusty wallis honda dallas',
    aliases: ['Rusty Wallis Honda'],
    slug: 'rusty-wallis-honda-dallas',
    street_address: '12277 E Northwest Hwy',
    city: 'Dallas',
    state: 'TX',
    zip_code: '75228',
    market: 'DFW',
    latitude: 32.8645,
    longitude: -96.6712,
    website: 'https://www.rustywallishonda.com',
    phone: '(214) 348-7500',
    dealer_group: 'Rusty Wallis Auto Group',
    brands: ['Honda'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Rusty Wallis Volkswagen Garland',
    normalized_name: 'rusty wallis volkswagen garland',
    aliases: ['Rusty Wallis VW'],
    slug: 'rusty-wallis-vw-garland',
    street_address: '12635 Lyndon B Johnson Fwy',
    city: 'Garland',
    state: 'TX',
    zip_code: '75041',
    market: 'DFW',
    latitude: 32.8612,
    longitude: -96.6645,
    website: 'https://www.rustywallisvw.com',
    phone: '(214) 349-2000',
    dealer_group: 'Rusty Wallis Auto Group',
    brands: ['Volkswagen'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },

  // 11. North Texas & Denton County Anchors
  {
    name: 'Bill Utter Ford Denton',
    normalized_name: 'bill utter ford denton',
    aliases: ['Bill Utter Ford'],
    slug: 'bill-utter-ford-denton',
    street_address: '4901 S I-35E',
    city: 'Denton',
    state: 'TX',
    zip_code: '76210',
    market: 'DFW',
    latitude: 33.1672,
    longitude: -97.0851,
    website: 'https://www.billutterford.com',
    phone: '(940) 321-7400',
    brands: ['Ford'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Classic Chrysler Dodge Jeep Ram FIAT of Denton',
    normalized_name: 'classic cdjr denton',
    aliases: ['Classic CDJR Denton'],
    slug: 'classic-cdjr-denton',
    street_address: '4984 S I-35E',
    city: 'Denton',
    state: 'TX',
    zip_code: '76210',
    market: 'DFW',
    latitude: 33.1651,
    longitude: -97.0872,
    website: 'https://www.classiccdjrdenton.com',
    phone: '(940) 498-9800',
    dealer_group: 'Classic Auto Group',
    brands: ['Chrysler', 'Dodge', 'Jeep', 'Ram', 'FIAT'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Eldorado Chevrolet McKinney',
    normalized_name: 'eldorado chevrolet mckinney',
    aliases: ['Eldorado Chevy'],
    slug: 'eldorado-chevrolet-mckinney',
    street_address: '2300 S Central Expy',
    city: 'McKinney',
    state: 'TX',
    zip_code: '75070',
    market: 'DFW',
    latitude: 33.1702,
    longitude: -96.6435,
    website: 'https://www.eldoradochevrolet.com',
    phone: '(972) 569-0101',
    brands: ['Chevrolet'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Eldorado Mazda McKinney',
    normalized_name: 'eldorado mazda mckinney',
    aliases: ['Eldorado Mazda'],
    slug: 'eldorado-mazda-mckinney',
    street_address: '2300 S Central Expy Suite B',
    city: 'McKinney',
    state: 'TX',
    zip_code: '75070',
    market: 'DFW',
    latitude: 33.1705,
    longitude: -96.6441,
    website: 'https://www.eldoradomazda.com',
    phone: '(972) 569-0100',
    brands: ['Mazda'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Brandon Tomes Subaru McKinney',
    normalized_name: 'brandon tomes subaru mckinney',
    aliases: ['Brandon Tomes Subaru', 'Subaru McKinney'],
    slug: 'brandon-tomes-subaru-mckinney',
    street_address: '1100 S Central Expy',
    city: 'McKinney',
    state: 'TX',
    zip_code: '75070',
    market: 'DFW',
    latitude: 33.1812,
    longitude: -96.6385,
    website: 'https://www.brandontomessubaru.com',
    phone: '(888) 473-1954',
    brands: ['Subaru'],
    dealership_type: 'both',
    is_active: true,
    is_claimed: false
  },

  // 12. Premier Independent Used Dealerships in DFW (Zero-pressure & institutional)
  {
    name: 'CarMax Plano North',
    normalized_name: 'carmax plano north',
    aliases: ['CarMax Plano'],
    slug: 'carmax-plano-north',
    street_address: '1300 N Central Expy',
    city: 'Plano',
    state: 'TX',
    zip_code: '75074',
    market: 'DFW',
    latitude: 33.0245,
    longitude: -96.7028,
    website: 'https://www.carmax.com/stores/7123',
    phone: '(972) 424-6000',
    dealer_group: 'CarMax Inc',
    brands: ['Multi-brand Used'],
    dealership_type: 'used',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'CarMax Fort Worth South',
    normalized_name: 'carmax fort worth south',
    aliases: ['CarMax Fort Worth'],
    slug: 'carmax-fort-worth-south',
    street_address: '8400 Anderson Blvd',
    city: 'Fort Worth',
    state: 'TX',
    zip_code: '76120',
    market: 'DFW',
    latitude: 32.7441,
    longitude: -97.1952,
    website: 'https://www.carmax.com/stores/7125',
    phone: '(817) 459-3300',
    dealer_group: 'CarMax Inc',
    brands: ['Multi-brand Used'],
    dealership_type: 'used',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'CarMax Irving West',
    normalized_name: 'carmax irving west',
    aliases: ['CarMax Irving'],
    slug: 'carmax-irving-west',
    street_address: '1500 E Airport Fwy',
    city: 'Irving',
    state: 'TX',
    zip_code: '75062',
    market: 'DFW',
    latitude: 32.8375,
    longitude: -96.9281,
    website: 'https://www.carmax.com/stores/7124',
    phone: '(972) 554-1200',
    dealer_group: 'CarMax Inc',
    brands: ['Multi-brand Used'],
    dealership_type: 'used',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'CarMax Garland East',
    normalized_name: 'carmax garland east',
    aliases: ['CarMax Garland'],
    slug: 'carmax-garland-east',
    street_address: '12715 Lyndon B Johnson Fwy',
    city: 'Garland',
    state: 'TX',
    zip_code: '75041',
    market: 'DFW',
    latitude: 32.8601,
    longitude: -96.6625,
    website: 'https://www.carmax.com/stores/7126',
    phone: '(972) 271-8800',
    dealer_group: 'CarMax Inc',
    brands: ['Multi-brand Used'],
    dealership_type: 'used',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Texas Hot Rides Addison',
    normalized_name: 'texas hot rides addison',
    aliases: ['Texas Hot Rides'],
    slug: 'texas-hot-rides-addison',
    street_address: '4508 McEwen Rd',
    city: 'Dallas',
    state: 'TX',
    zip_code: '75244',
    market: 'DFW',
    latitude: 32.9325,
    longitude: -96.8398,
    website: 'https://www.texashotrides.com',
    phone: '(214) 244-2956',
    brands: ['Performance & Specialty Used'],
    dealership_type: 'used',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'Earth MotorCars Carrollton',
    normalized_name: 'earth motorcars carrollton',
    aliases: ['Earth MotorCars'],
    slug: 'earth-motorcars-carrollton',
    street_address: '16410 Midway Rd',
    city: 'Carrollton',
    state: 'TX',
    zip_code: '75001',
    market: 'DFW',
    latitude: 32.9735,
    longitude: -96.8385,
    website: 'https://www.earthmotorcars.com',
    phone: '(214) 483-9040',
    brands: ['Exotic & Luxury Used'],
    dealership_type: 'used',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'EchoPark Automotive Grand Prairie',
    normalized_name: 'echopark automotive grand prairie',
    aliases: ['EchoPark Grand Prairie'],
    slug: 'echopark-grand-prairie',
    street_address: '1600 W I-20',
    city: 'Grand Prairie',
    state: 'TX',
    zip_code: '75052',
    market: 'DFW',
    latitude: 32.6778,
    longitude: -97.0265,
    website: 'https://www.echopark.com/dealerships/grand-prairie',
    phone: '(972) 349-8800',
    dealer_group: 'Sonic Automotive',
    brands: ['Multi-brand Used'],
    dealership_type: 'used',
    is_active: true,
    is_claimed: false
  },
  {
    name: 'EchoPark Automotive Plano',
    normalized_name: 'echopark automotive plano',
    aliases: ['EchoPark Plano'],
    slug: 'echopark-plano',
    street_address: '4200 W Plano Pkwy',
    city: 'Plano',
    state: 'TX',
    zip_code: '75093',
    market: 'DFW',
    latitude: 33.0185,
    longitude: -96.7825,
    website: 'https://www.echopark.com/dealerships/plano',
    phone: '(972) 996-5700',
    dealer_group: 'Sonic Automotive',
    brands: ['Multi-brand Used'],
    dealership_type: 'used',
    is_active: true,
    is_claimed: false
  }
];

/**
 * Helper function to transform a seed dealership into a full Dealership object
 * Initial metrics are initialized with zero reviews, zero fabricated data, and neutral baseline scores.
 */
export function seedToDealership(seed: SeedDealership, id: string = crypto.randomUUID()): Dealership {
  const now = new Date().toISOString();
  return {
    id,
    name: seed.name,
    normalized_name: seed.normalized_name,
    aliases: seed.aliases,
    slug: seed.slug,
    street_address: seed.street_address,
    city: seed.city,
    state: seed.state,
    zip_code: seed.zip_code,
    market: seed.market,
    latitude: seed.latitude ?? null,
    longitude: seed.longitude ?? null,
    website: seed.website,
    phone: seed.phone,
    dealer_group: seed.dealer_group ?? null,
    brands: seed.brands,
    dealership_type: seed.dealership_type,
    is_active: seed.is_active,
    is_claimed: seed.is_claimed,
    claimed_by: null,
    claimed_at: null,
    verified_contact_email: null,
    // Aggregates start clean and unreviewed (0 fabricated content)
    overall_rating: 0.0,
    review_count: 0,
    verified_review_count: 0,
    price_transparency_score: 50, // Neutral 50 baseline until community submissions
    would_recommend_pct: 0,
    avg_reported_doc_fee: null,
    advertised_price_honored_pct: 0,
    mandatory_addons_reported_pct: 0,
    created_at: now,
    updated_at: now,
    deleted_at: null
  };
}
